"use strict";
let number = 12.5;
console.log(typeof number);
let number2 = 245;
console.log(typeof number2);
let greetings = "Hello";
console.log(typeof greetings);
let meaning = undefined;
console.log(typeof meaning);
let nothing = null;
console.log(typeof nothing);
let truth = true;
console.log(typeof truth);
let value = [1, 5, 7, 12, 3, "значение"];
console.log(typeof value);
let nickName = { Вася: "Имя" };
console.log(typeof nickName);
let functionX = function () {};
console.log(typeof functionX);
